In [1]:
import pandas as pd
from sklearn.datasets import load_breast_cancer
import plotly.express as px
import numpy as np

1️⃣ - Realize a leitura do dataset breast_cancer

In [2]:
cancer = load_breast_cancer()
x_cancer = cancer.data
y_cancer = cancer.target

2️⃣ - Transformando os dados em um DataFrame

In [3]:
x_cancer = pd.DataFrame(x_cancer, columns=cancer['feature_names'])
pd.set_option('display.max_columns', None)
x_cancer['target'] = y_cancer
df_cancer = x_cancer

3️⃣ - Analise Exploratoria dos Dados (EDA)

- Fundação dos dados

In [4]:
df_cancer.head().style.set_caption('Primeiras 5 linhas do dataset')

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelapp.py", line 739, in start
    self.io_loop.start()
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 437, in dispatch_shell
    await result
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\ipkernel.py", line 359, in execute_request
    await super().execute_request(stream, ident, parent)
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\ipkernel.py", line 446, in do_execute
    res = shell.run_cell(
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\anton\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\anton\AppData\Local\Temp\ipykernel_9752\2767106688.py", line 1, in <module>
    df_cancer.head().style.set_caption('Primeiras 5 linhas do dataset')
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\frame.py", line 1447, in style
    from pandas.io.formats.style import Styler
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\formats\style.py", line 85, in <module>
    import matplotlib as mpl
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 144, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, _cm, cbook, scale
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\scale.py", line 22, in <module>
    from matplotlib.ticker import (
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\ticker.py", line 138, in <module>
    from matplotlib import transforms as mtransforms
  File "c:\Users\anton\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\transforms.py", line 49, in <module>
    from matplotlib._path import (

AttributeError: _ARRAY_API not found

In [5]:
df_cancer.sample(5).style.set_caption("5 linhas aleatorias do dataset")

In [6]:
df_cancer.tail().style.set_caption("Ultimas 5 linhas do dataset")

In [25]:
# Exibe os nomes das colunas
print('-' * 40)
print('Exibindo os nomes das colunas do Dataset')
print('-' * 40)
df_cancer.columns = [col.replace(" ", "_") for col in df_cancer.columns]
for i in df_cancer.columns:
    print(f'-{i}')

----------------------------------------
Exibindo os nomes das colunas do Dataset
----------------------------------------
-mean_radius
-mean_texture
-mean_perimeter
-mean_area
-mean_smoothness
-mean_compactness
-mean_concavity
-mean_concave_points
-mean_symmetry
-mean_fractal_dimension
-radius_error
-texture_error
-perimeter_error
-area_error
-smoothness_error
-compactness_error
-concavity_error
-concave_points_error
-symmetry_error
-fractal_dimension_error
-worst_radius
-worst_texture
-worst_perimeter
-worst_area
-worst_smoothness
-worst_compactness
-worst_concavity
-worst_concave_points
-worst_symmetry
-worst_fractal_dimension
-target

In [29]:
print("-" * 50)
print("Informações acerca do dataset")
print("-" * 50)
df_cancer.info() # Informacoes sobre as colunas

--------------------------------------------------
Informações acerca do dataset
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean_radius              569 non-null    float64
 1   mean_texture             569 non-null    float64
 2   mean_perimeter           569 non-null    float64
 3   mean_area                569 non-null    float64
 4   mean_smoothness          569 non-null    float64
 5   mean_compactness         569 non-null    float64
 6   mean_concavity           569 non-null    float64
 7   mean_concave_points      569 non-null    float64
 8   mean_symmetry            569 non-null    float64
 9   mean_fractal_dimension   569 non-null    float64
 10  radius_error             569 non-null    float64
 11  texture_error            569 non-null    float64
 12  perimeter_error          569 non-null    float64
 13  area_error               569 non-null    float64
 14  smoothness_error         569 non-null    float64
 15  compactness_error        569 non-null    float64
 16  concavity_error          569 non-null    float64
 17  concave_points_error     569 non-null    float64
 18  symmetry_error           569 non-null    float64
 19  fractal_dimension_error  569 non-null    float64
 20  worst_radius             569 non-null    float64
 21  worst_texture            569 non-null    float64
 22  worst_perimeter          569 non-null    float64
 23  worst_area               569 non-null    float64
 24  worst_smoothness         569 non-null    float64
 25  worst_compactness        569 non-null    float64
 26  worst_concavity          569 non-null    float64
 27  worst_concave_points     569 non-null    float64
 28  worst_symmetry           569 non-null    float64
 29  worst_fractal_dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

- Analise estrutural

In [30]:
# Exibe a quantidade de linhas e colunas
print("-" * 25)
print("Dimensões do DataFrame:")
print("-" * 25)
print(f"Linhas: \t {df_cancer.shape[0]}")
print(f"Colunas:\t {df_cancer.shape[1]}")

-------------------------
Dimensões do DataFrame:
-------------------------
Linhas: 	 569
Colunas:	 31

In [34]:
print('-'*30)
print('Verificando se a dados nulos')
print('-'*30)
df_cancer.isnull().sum() # Verificando dados nulos

------------------------------
Verificando se a dados nulos
------------------------------

mean_radius                0
mean_texture               0
mean_perimeter             0
mean_area                  0
mean_smoothness            0
mean_compactness           0
mean_concavity             0
mean_concave_points        0
mean_symmetry              0
mean_fractal_dimension     0
radius_error               0
texture_error              0
perimeter_error            0
area_error                 0
smoothness_error           0
compactness_error          0
concavity_error            0
concave_points_error       0
symmetry_error             0
fractal_dimension_error    0
worst_radius               0
worst_texture              0
worst_perimeter            0
worst_area                 0
worst_smoothness           0
worst_compactness          0
worst_concavity            0
worst_concave_points       0
worst_symmetry             0
worst_fractal_dimension    0
target                     0
dtype: int64

In [37]:
print('-'*35)
print('Verificando se a dados duplicados')
print('-'*35)
df_cancer.duplicated().sum() # Verifica se a valores duplicados no dataframe

-----------------------------------
Verificando se a dados duplicados
-----------------------------------

np.int64(0)

In [40]:
print('-'*50)
print('Verificando se a dados duplicados na coluna ID')
print('-'*50)
df_cancer.index[df_cancer.index.duplicated()] # Verifica se a valores duplicados na coluna ID

--------------------------------------------------
Verificando se a dados duplicados na coluna ID
--------------------------------------------------

Index([], dtype='int64')

In [41]:
# Itera sobre as colunas e verifica a unicidade
for coluna in df_cancer.columns:
    num_unicos = df_cancer[coluna].nunique()
    num_linhas = df_cancer.shape[0]
    if num_unicos == num_linhas:
        print(f"A coluna '{coluna}' possui valores únicos.")

In [59]:
# Contagem de valores únicos por coluna
print("-" * 40)
print("Contagem de valores únicos por coluna:")
print("-" * 40)
print(df_cancer.nunique())

----------------------------------------
Contagem de valores únicos por coluna:
----------------------------------------
mean_radius                456
mean_texture               479
mean_perimeter             522
mean_area                  539
mean_smoothness            474
mean_compactness           537
mean_concavity             537
mean_concave_points        542
mean_symmetry              432
mean_fractal_dimension     499
radius_error               540
texture_error              519
perimeter_error            533
area_error                 528
smoothness_error           547
compactness_error          541
concavity_error            533
concave_points_error       507
symmetry_error             498
fractal_dimension_error    545
worst_radius               457
worst_texture              511
worst_perimeter            514
worst_area                 544
worst_smoothness           411
worst_compactness          529
worst_concavity            539
worst_concave_points       492
worst_symmetry             500
worst_fractal_dimension    535
target                       2
dtype: int64

In [15]:
df_cancer.describe() #Resumo estatistico dos dados

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,mean_fractal_dimension,radius_error,texture_error,perimeter_error,area_error,smoothness_error,compactness_error,concavity_error,concave_points_error,symmetry_error,fractal_dimension_error,worst_radius,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,0.405172,1.216853,2.866059,40.337079,0.007041,0.025478,0.031894,0.011796,0.020542,0.003795,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,0.277313,0.551648,2.021855,45.491006,0.003003,0.017908,0.030186,0.006170,0.008266,0.002646,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,0.111500,0.360200,0.757000,6.802000,0.001713,0.002252,0.000000,0.000000,0.007882,0.000895,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,0.232400,0.833900,1.606000,17.850000,0.005169,0.013080,0.015090,0.007638,0.015160,0.002248,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,0.324200,1.108000,2.287000,24.530000,0.006380,0.020450,0.025890,0.010930,0.018730,0.003187,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,0.478900,1.474000,3.357000,45.190000,0.008146,0.032450,0.042050,0.014710,0.023480,0.004558,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,2.873000,4.885000,21.980000,542.200000,0.031130,0.135400,0.396000,0.052790,0.078950,0.029840,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [49]:
#-Distribuicao das classes e contando quantas amostras são malignas (0) e benignas (1).
print('-'*25)
print('Contagem por amostras')
print('-'*25)
agrupando_target = df_cancer.groupby(['target']).size()
agrupando_target.index = ['Benigno (0)', 'Maligno (1)']
agrupando_target

-------------------------
Contagem por amostras
-------------------------

Benigno (0)    212
Maligno (1)    357
dtype: int64

In [54]:
# Verificando a distribuição em porcentagem
print('-'*30)
print("Contagem por amostras em %:")
print('-'*30)
agrupando_target = df_cancer['target'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%'
agrupando_target.index = ['Benigno (0)', 'Maligno (1)']
agrupando_target

------------------------------
Contagem por amostras em %:
------------------------------

Benigno (0)    62.74%
Maligno (1)    37.26%
Name: proportion, dtype: object

In [17]:
# Análise descritiva por classe
df_cancer.groupby('target').describe()

       mean_radius                                                             \
             count       mean       std     min     25%     50%    75%    max
target
0            212.0  17.462830  3.203971  10.950  15.075  17.325  19.59  28.11
1            357.0  12.146524  1.780512   6.981  11.080  12.200  13.37  17.85

       mean_texture                                                      \
              count       mean       std    min      25%    50%     75%
target
0             212.0  21.604906  3.779470  10.38  19.3275  21.46  23.765
1             357.0  17.914762  3.995125   9.71  15.1500  17.39  19.760

              mean_perimeter                                                \
          max          count        mean        std    min     25%     50%
target
0       39.28          212.0  115.365377  21.854653  71.90  98.745  114.20
1       33.81          357.0   78.075406  11.807438  43.79  70.870   78.18

                       mean_area                                               \
            75%    max     count        mean         std    min    25%    50%
target
0       129.925  188.5     212.0  978.376415  367.937978  361.6  705.3  932.0
1        86.100  114.6     357.0  462.790196  134.287118  143.5  378.2  458.4

                        mean_smoothness                                        \
            75%     max           count      mean       std      min      25%
target
0       1203.75  2501.0           212.0  0.102898  0.012608  0.07371  0.09401
1        551.10   992.1           357.0  0.092478  0.013446  0.05263  0.08306

                                  mean_compactness                      \
            50%       75%     max            count      mean       std
target
0       0.10220  0.110925  0.1447            212.0  0.145188  0.053987
1       0.09076  0.100700  0.1634            357.0  0.080085  0.033750

                                                   mean_concavity            \
            min      25%      50%      75%     max          count      mean
target
0       0.04605  0.10960  0.13235  0.17240  0.3454          212.0  0.160775
1       0.01938  0.05562  0.07529  0.09755  0.2239          357.0  0.046058

                                                               \
             std      min       25%      50%      75%     max
target
0       0.075019  0.02398  0.109525  0.15135  0.20305  0.4268
1       0.043442  0.00000  0.020310  0.03709  0.05999  0.4108

       mean_concave_points                                                 \
                     count      mean       std      min      25%      50%
target
0                    212.0  0.087990  0.034374  0.02031  0.06462  0.08628
1                    357.0  0.025717  0.015909  0.00000  0.01502  0.02344

                          mean_symmetry                                       \
             75%      max         count      mean       std     min      25%
target
0       0.103175  0.20120         212.0  0.192909  0.027638  0.1308  0.17405
1       0.032510  0.08534         357.0  0.174186  0.024807  0.1060  0.15800

                                mean_fractal_dimension                      \
           50%      75%     max                  count      mean       std
target
0       0.1899  0.20985  0.3040                  212.0  0.062680  0.007573
1       0.1714  0.18900  0.2743                  357.0  0.062867  0.006747

                                                       radius_error            \
            min       25%       50%       75%      max        count      mean
target
0       0.04996  0.056598  0.061575  0.067075  0.09744        212.0  0.609083
1       0.05185  0.058530  0.061540  0.065760  0.09575        357.0  0.284082

                                                           texture_error  \
             std     min       25%     50%     75%     max         count
target
0       0.345039  0.1938  0.390375  0.5472  0.7573  2.8730         212.0
1       0.112570  0.1115  0.207300  0.2575  0.3416  0.8811         357.0

                                                                      \
            mean       std     min       25%     50%      75%    max
target
0       1.210915  0.483178  0.3621  0.892825  1.1025  1.42925  3.568
1       1.220380  0.589180  0.3602  0.795900  1.1080  1.49200  4.885

       perimeter_error                                                      \
                 count      mean       std    min     25%     50%      75%
target
0                212.0  4.323929  2.568546  1.334  2.7155  3.6795  5.20625
1                357.0  2.000321  0.771169  0.757  1.4450  1.8510  2.38800

               area_error                                                 \
           max      count       mean        std     min      25%     50%
target
0       21.980      212.0  72.672406  61.355268  13.990  35.7625  58.455
1        5.118      357.0  21.135148   8.843472   6.802  15.2600  19.630

                      smoothness_error                                \
          75%     max            count      mean       std       min
target
0       94.00  542.20            212.0  0.006780  0.002890  0.002667
1       25.03   77.11            357.0  0.007196  0.003061  0.001713

                                              compactness_error            \
             25%       50%       75%      max             count      mean
target
0       0.005085  0.006209  0.007971  0.03113             212.0  0.032281
1       0.005212  0.006530  0.008534  0.02177             357.0  0.021438

                                                                \
             std       min       25%      50%      75%     max
target
0       0.018387  0.008422  0.019662  0.02859  0.03891  0.1354
1       0.016352  0.002252  0.011320  0.01631  0.02589  0.1064

       concavity_error                                                   \
                 count      mean       std      min       25%       50%
target
0                212.0  0.041824  0.021603  0.01101  0.026998  0.037125
1                357.0  0.025997  0.032918  0.00000  0.010990  0.018400

                         concave_points_error                                \
             75%     max                count      mean       std       min
target
0       0.050443  0.1438                212.0  0.015060  0.005517  0.005174
1       0.030560  0.3960                357.0  0.009858  0.005709  0.000000

                                              symmetry_error            \
             25%       50%       75%      max          count      mean
target
0       0.011415  0.014205  0.017497  0.04090          212.0  0.020472
1       0.006433  0.009061  0.011870  0.05279          357.0  0.020584

                                                                  \
             std       min       25%      50%       75%      max
target
0       0.010065  0.007882  0.014615  0.01770  0.022132  0.07895
1       0.006999  0.009539  0.015600  0.01909  0.024060  0.06146

       fractal_dimension_error                                          \
                         count      mean       std       min       25%
target
0                        212.0  0.004062  0.002041  0.001087  0.002688
1                        357.0  0.003636  0.002938  0.000895  0.002074

                                    worst_radius                              \
             50%       75%      max        count       mean       std    min
target
0       0.003739  0.004892  0.01284        212.0  21.134811  4.283569  12.84
1       0.002808  0.004174  0.02984        357.0  13.379801  1.981368   7.93

                                     worst_texture                       \
          25%    50%      75%    max         count       mean       std
target
0       17.73  20.59  23.8075  36.04         212.0  29.318208  5.434804
1       12.08  13.35  14.8000  19.82         357.0  23.515070  5.493955

                                             worst_perimeter              \
          min      25%     50%    75%    max           count        mean
target
0       16.67  25.7825  28.945  32.69  49.54           212.0  141.370330
1       12.02  19.5800  22.820  26.51  41.78           357.0   87.005938

                                                         worst_area  \
              std    min      25%     50%     75%    max      count
target
0       29.457055  85.10  119.325  138.00  159.80  251.2      212.0
1       13.527091  50.41   78.270   86.92   96.59  127.1      357.0

                                                                        \
               mean         std    min    25%     50%      75%     max
target
0       1422.286321  597.967743  508.1  970.3  1303.0  1712.75  4254.0
1        558.899440  163.601424  185.2  447.1   547.4   670.00  1210.0

       worst_smoothness                                                  \
                  count      mean       std      min       25%      50%
target
0                 212.0  0.144845  0.021870  0.08822  0.130475  0.14345
1                 357.0  0.124959  0.020013  0.07117  0.110400  0.12540

                         worst_compactness                               \
             75%     max             count      mean       std      min
target
0       0.155975  0.2226             212.0  0.374824  0.170372  0.05131
1       0.137600  0.2006             357.0  0.182673  0.092180  0.02729

                                           worst_concavity            \
             25%      50%      75%     max           count      mean
target
0       0.244475  0.35635  0.44785  1.0580           212.0  0.450606
1       0.112000  0.16980  0.23020  0.5849           357.0  0.166238

                                                              \
             std      min       25%     50%       75%    max
target
0       0.181507  0.02398  0.326425  0.4049  0.556175  1.170
1       0.140368  0.00000  0.077080  0.1412  0.221600  1.252

       worst_concave_points                                                 \
                      count      mean       std      min      25%      50%
target
0                     212.0  0.182237  0.046308  0.02899  0.15275  0.18200
1                     357.0  0.074444  0.035797  0.00000  0.05104  0.07431

                        worst_symmetry                                      \
             75%    max          count      mean       std     min     25%
target
0       0.210675  0.291          212.0  0.323468  0.074685  0.1565  0.2765
1       0.097490  0.175          357.0  0.270246  0.041745  0.1566  0.2406

                                 worst_fractal_dimension                      \
           50%       75%     max                   count      mean       std
target
0       0.3103  0.359225  0.6638                   212.0  0.091530  0.021553
1       0.2687  0.298300  0.4228                   357.0  0.079442  0.013804


            min       25%      50%       75%     max
target
0       0.05504  0.076302  0.08760  0.102625  0.2075
1       0.05521  0.070090  0.07712  0.085410  0.1486